#!/bin/sh
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$ROOT"

[ "$(cat VERSION)" = "1.2.8" ]
grep -Fq '# Wheelchair 1.2.8' README.md
for f in RELEASE_NOTES_1_2_8.md RELEASE_PROOF_1_2_8.md RELEASE_GATES_1_2_8.txt; do
  [ -s "$f" ]
done
grep -Fq 'NATIVE256_NORMAL_BUILD_MATURITY_AUTHORITY=PASS' RELEASE_GATES_1_2_8.txt
grep -Fq 'NATIVE256_SECOND_STAGE_DIAGNOSTIC_INJECTION=0' RELEASE_GATES_1_2_8.txt
grep -Fq 'NATIVE256_HIGH_PRESSURE_AVX2_YMM_ONLY=PASS' RELEASE_GATES_1_2_8.txt
grep -Fq 'NATIVE256_HIGH_PRESSURE_COUPLED_EXECUTION=PASS' RELEASE_GATES_1_2_8.txt
grep -Fq 'NATIVE256_GENERATED_WORKLOAD_BLIND=PASS' RELEASE_GATES_1_2_8.txt
grep -Fq 'WHEELCHAIR_NATIVE256_MATURITY_1_2_8=PASS' RELEASE_GATES_1_2_8.txt
grep -Fq 'WHEELCHAIR_1_2_8_FINAL=PASS' RELEASE_GATES_1_2_8.txt

echo 'WHEELCHAIR_1_2_8_RELEASE_DOCUMENTS=PASS'
echo 'WHEELCHAIR_1_2_8_FINAL=PASS'
